baseURL = "https://canx.me/"
languageCode = "en-us"
title = "can."
theme = "black-and-light"
author = "can."
hasCJKLanguage = true
publishDir = "/var/www/canxme"

[[menu.main]]
    name = "GitHub"
    url = "https://github.com/cannium"
[[menu.main]]
    name = "About"
    url = "/about"

[params]
    sitename = "can."